version: '3.8'

networks:
  payou-app:
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - payou-app

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - payou-app

  mysql:
    image: mysql:8
    container_name: mysql
    tty: true
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: payouapp
      MYSQL_USER: payou
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
   
    networks:
      - payou-app

